# Generated by Django 4.2.11 on 2024-04-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["username"], name="base_item_usernam_0d5e76_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(fields=["email"], name="base_item_email_da9c55_idx"),
        ),
    ]
