# Generated by Django 4.2.11 on 2024-04-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_item_base_item_usernam_0d5e76_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="media/"),
        ),
    ]
